// <auto-generated-by-tooling />
// 本文件由 Python 版 database.py 的 SCHEMA / SEED_DICT 生成，请勿手工编辑。
// 生成命令见 potms-dotnet/tools/gen-schema.py
//
// 目的：四个语言版本（Python / Go / Rust / .NET）共用同一个 data.db，
//       schema 必须逐字节一致，故由脚本从单一来源生成而非手抄。
namespace POTMS.Data;

public static class Schema
{
    public const string Ddl = @"
CREATE TABLE IF NOT EXISTS users (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS personnel_info (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    unit TEXT NOT NULL,
    department TEXT NOT NULL,
    name TEXT NOT NULL,
    gender TEXT NOT NULL,
    birth_date TEXT NOT NULL,
    id_number TEXT,
    work_start_date TEXT,
    education TEXT,
    degree TEXT,
    title TEXT,
    rank TEXT NOT NULL,
    political_status TEXT NOT NULL,
    party_join_date TEXT,
    position TEXT NOT NULL,
    operator TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS personnel_filing (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    personnel_info_id INTEGER REFERENCES personnel_info(id),
    surname TEXT NOT NULL,
    given_name TEXT NOT NULL,
    gender TEXT NOT NULL,
    birth_date TEXT NOT NULL,
    id_number TEXT NOT NULL,
    residence TEXT NOT NULL,
    political_status TEXT NOT NULL,
    work_unit TEXT NOT NULL,
    position_or_title TEXT NOT NULL,
    supervisor_unit TEXT NOT NULL,
    tag TEXT NOT NULL DEFAULT '新增',
    informed TEXT NOT NULL DEFAULT '否',
    status TEXT NOT NULL DEFAULT 'active',
    remarks TEXT,
    replaced_by_id INTEGER,
    operator TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS certificates (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    personnel_filing_id INTEGER NOT NULL REFERENCES personnel_filing(id),
    unit TEXT NOT NULL,
    department TEXT NOT NULL,
    name TEXT NOT NULL,
    passport_no TEXT,
    passport_expiry TEXT,
    passport_submit_date TEXT,
    hm_pass_no TEXT,
    hm_pass_expiry TEXT,
    hm_pass_submit_date TEXT,
    tw_pass_no TEXT,
    tw_pass_expiry TEXT,
    tw_pass_submit_date TEXT,
    operator TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS travel_details (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    personnel_filing_id INTEGER NOT NULL REFERENCES personnel_filing(id),
    unit TEXT NOT NULL,
    department TEXT NOT NULL,
    name TEXT NOT NULL,
    position TEXT NOT NULL,
    title TEXT,
    id_number TEXT NOT NULL,
    destination_passport TEXT NOT NULL,
    category TEXT NOT NULL,
    travel_dates TEXT NOT NULL,
    approval_date TEXT,
    need_new_passport TEXT NOT NULL DEFAULT '否',
    passport_no TEXT,
    passport_collect_date TEXT,
    passport_return_date TEXT,
    actual_return_date TEXT,
    trip_status TEXT DEFAULT 'normal',
    cancel_date TEXT,
    operator TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS decontrol_filing (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    personnel_filing_id INTEGER NOT NULL REFERENCES personnel_filing(id),
    surname TEXT NOT NULL,
    given_name TEXT NOT NULL,
    gender TEXT NOT NULL,
    birth_date TEXT NOT NULL,
    id_number TEXT NOT NULL,
    residence TEXT NOT NULL,
    political_status TEXT NOT NULL,
    work_unit TEXT NOT NULL,
    supervisor_unit TEXT NOT NULL,
    submit_unit_name TEXT NOT NULL,
    submit_unit_type TEXT NOT NULL,
    submit_contact TEXT NOT NULL,
    submit_phone TEXT NOT NULL,
    batch_no TEXT NOT NULL,
    reason TEXT NOT NULL,
    decontrol_date TEXT,
    cert_handover_date TEXT,
    operator TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_submit_unit (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    contact TEXT,
    phone TEXT,
    sort_order INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS cert_issuance (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    travel_id INTEGER REFERENCES travel_details(id),
    personnel_filing_id INTEGER NOT NULL REFERENCES personnel_filing(id),
    holder_name TEXT NOT NULL,
    id_number TEXT,
    cert_types TEXT NOT NULL,
    cert_nos TEXT,
    issue_date TEXT NOT NULL,
    issuer TEXT NOT NULL,
    sign_image BLOB,
    sign_meta TEXT,
    return_date TEXT,
    return_sign_image BLOB,
    return_sign_meta TEXT,
    return_operator TEXT,
    status TEXT NOT NULL DEFAULT 'issued',
    void_reason TEXT,
    remarks TEXT,
    operator TEXT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS attachments (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    travel_id INTEGER NOT NULL REFERENCES travel_details(id) ON DELETE CASCADE,
    file_name TEXT NOT NULL,
    file_path TEXT NOT NULL,
    file_type TEXT NOT NULL,
    file_size INTEGER NOT NULL,
    uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS sys_dict (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    category TEXT NOT NULL,
    code TEXT NOT NULL,
    value TEXT NOT NULL,
    sort_order INTEGER DEFAULT 0,
    UNIQUE(category, code)
);

CREATE TABLE IF NOT EXISTS sys_org (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    name TEXT NOT NULL,
    parent_id INTEGER DEFAULT 0,
    sort_order INTEGER DEFAULT 0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS operation_logs (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    operator TEXT NOT NULL,
    action TEXT NOT NULL,
    target_type TEXT NOT NULL,
    target_id INTEGER,
    detail TEXT,
    ip_address TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
";

    /// <summary>字典种子数据：(分类, 代码, 显示值, 排序)</summary>
    public static readonly (string Category, string Code, string Value, int SortOrder)[] SeedDict =
    {
        ("education", "01", "博士研究生", 1),
        ("education", "02", "硕士研究生", 2),
        ("education", "03", "大学本科", 3),
        ("education", "04", "大学专科", 4),
        ("education", "05", "中专", 5),
        ("education", "06", "高中", 6),
        ("education", "07", "初中及以下", 7),
        ("degree", "01", "博士", 1),
        ("degree", "02", "硕士", 2),
        ("degree", "03", "学士", 3),
        ("degree", "99", "无", 4),
        ("title", "01", "正高", 1),
        ("title", "02", "副高", 2),
        ("title", "03", "中级", 3),
        ("title", "04", "初级", 4),
        ("title", "99", "无", 5),
        ("rank", "01", "处级", 1),
        ("rank", "02", "副处级", 2),
        ("rank", "03", "正科", 3),
        ("rank", "04", "副科", 4),
        ("rank", "05", "科员", 5),
        ("rank", "99", "其他", 6),
        ("political_status", "01", "中共党员", 1),
        ("political_status", "02", "中共预备党员", 2),
        ("political_status", "03", "共青团员", 3),
        ("political_status", "04", "民革会员", 4),
        ("political_status", "05", "民盟盟员", 5),
        ("political_status", "06", "民建会员", 6),
        ("political_status", "07", "民进会员", 7),
        ("political_status", "08", "农工党党员", 8),
        ("political_status", "09", "致工党党员", 9),
        ("political_status", "10", "九三学社社员", 10),
        ("political_status", "99", "群众", 11),
        ("travel_category", "01", "旅游", 1),
        ("travel_category", "02", "探亲", 2),
        ("travel_category", "03", "访友", 3),
        ("travel_category", "04", "商务", 4),
        ("travel_category", "05", "留学", 5),
        ("travel_category", "99", "其他", 6),
        ("submit_unit_type", "01", "党政机关", 1),
        ("submit_unit_type", "02", "金融系统", 2),
        ("submit_unit_type", "03", "教科文卫系统", 3),
        ("submit_unit_type", "04", "国有大中型企业单位", 4),
        ("submit_unit_type", "99", "其他单位", 5),
        ("supervisor_unit", "S01", "人事处", 1),
        ("cert_type", "01", "因私护照", 1),
        ("cert_type", "02", "往来港澳通行证", 2),
        ("cert_type", "03", "大陆居民往来台湾通行证", 3),
    };
}
