#!/usr/bin/env python3
"""从 Python 版 database.py 生成 .NET 版的 Data/Schema.cs。

四个语言版本（Python / Go / Rust / .NET）共用同一个 data.db，
schema 必须逐字节一致。手抄容易漂移，故由本脚本从单一来源生成。

用法（在仓库根目录执行）：
    python3 potms-dotnet/tools/gen-schema.py

改动 database.py 的 SCHEMA 或 SEED_DICT 后须重新运行本脚本，
CI 会校验生成结果与提交内容一致（见 .github/workflows/build-dotnet.yml）。
"""
import io
import os
import re
import sys

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
SRC = os.path.join(ROOT, "database.py")
DST = os.path.join(ROOT, "potms-dotnet", "src", "POTMS", "Data", "Schema.cs")


def generate() -> str:
    src = open(SRC, encoding="utf-8").read()
    m = re.search(r'SCHEMA\s*=\s*"""(.*?)"""', src, re.S)
    if not m:
        sys.exit("未能在 database.py 中定位 SCHEMA 常量")
    schema = m.group(1)
    seed = re.findall(r'^\s*\("([a-z_]+)",\s*"([^"]+)",\s*"([^"]+)",\s*(\d+)\),', src, re.M)
    if not seed:
        sys.exit("未能在 database.py 中解析 SEED_DICT")

    out = io.StringIO()
    out.write("// <auto-generated-by-tooling />\n")
    out.write("// 本文件由 Python 版 database.py 的 SCHEMA / SEED_DICT 生成，请勿手工编辑。\n")
    out.write("// 重新生成： python3 potms-dotnet/tools/gen-schema.py\n")
    out.write("//\n")
    out.write("// 目的：四个语言版本（Python / Go / Rust / .NET）共用同一个 data.db，\n")
    out.write("//       schema 必须逐字节一致，故由脚本从单一来源生成而非手抄。\n")
    out.write("namespace POTMS.Data;\n\n")
    out.write("public static class Schema\n{\n")
    out.write('    public const string Ddl = @"')
    out.write(schema.replace('"', '""'))   # C# 逐字字符串中的引号需双写
    out.write('";\n\n')
    out.write("    /// <summary>字典种子数据：(分类, 代码, 显示值, 排序)</summary>\n")
    out.write("    public static readonly (string Category, string Code, string Value, int SortOrder)[] SeedDict =\n")
    out.write("    {\n")
    for cat, code, val, order in seed:
        out.write(f'        ("{cat}", "{code}", "{val}", {order}),\n')
    out.write("    };\n}\n")
    return out.getvalue()


if __name__ == "__main__":
    content = generate()
    if "--check" in sys.argv:
        current = open(DST, encoding="utf-8").read() if os.path.exists(DST) else ""
        if current != content:
            sys.exit("Schema.cs 与 database.py 不同步，请运行： "
                     "python3 potms-dotnet/tools/gen-schema.py")
        print("Schema.cs 与 database.py 同步 ✓")
    else:
        os.makedirs(os.path.dirname(DST), exist_ok=True)
        open(DST, "w", encoding="utf-8").write(content)
        print(f"已生成 {os.path.relpath(DST, ROOT)}")
